### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by Rocklarry** [didianV5/voteApp#2]
你好！
打开浏览器的是就报这个错

Store path:/home/test3/.hfc-key-store
Failed to query successfully :: Error: Failed to get user1.... run registerUser.js

  SyntaxError: /home/test3/go/src/github.com/hyperledger/voteApp/app/views/index.ejs:28
      26|             </thead>
      27|             <tbody>
   >> 28|                 <% 
      29|                     jsonResult = JSON.parse(result)
      30|                     for(var i=0; i<jsonResult.length; i++) { 
      31|                 %>
  
  Unexpected token u in JSON at position 0
      at JSON.parse (<anonymous>)
      at eval (eval at compile (/home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:15:39)
      at returnedFn (/home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/ejs/lib/ejs.js:580:17)
      at /home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/consolidate/lib/consolidate.js:651:16
      at /home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/consolidate/lib/consolidate.js:162:5
      at Promise._execute (/home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/bluebird/js/release/debuggability.js:303:9)
      at Promise._resolveFromExecutor (/home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/bluebird/js/release/promise.js:483:18)
      at new Promise (/home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/bluebird/js/release/promise.js:79:10)
      at promisify (/home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/consolidate/lib/consolidate.js:155:10)
      at Function.exports.ejs.render (/home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/consolidate/lib/consolidate.js:647:10)
      at /home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/consolidate/lib/consolidate.js:183:27
      at /home/test3/go/src/github.com/hyperledger/voteApp/app/node_modules/consolidate/lib/consolidate.js:101:5
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by xizyj** [comment]
我也是报这个错

**Comment by zuo8787** [comment]
因为result此时为空，外面加上if判断，包住代码
if(result){
.....
}

**Comment by Android-sunshine** [comment]
我到这一步报错

node registerUser.js
 Store path:/Users/sunshine/Downloads/区块链/课程1/fabric_0122/voteApp/app/hfc-key-store
Successfully loaded admin from persistence
Failed to register: Error: fabric-ca request register failed with errors [[{"code":20,"message":"Authentication failure"}]]
